# -*- coding: utf-8 -*-
"""Prak Algo 9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s7g7RVse1bW6mmbvI5E-O5Avta2K83YD
"""

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')

def list_ke_tuple():
    input_list = input("Masukkan elemen-elemen list (pisahkan dengan spasi): ").split()
    tuple_result = tuple(input_list)
    print("List yang dimasukkan:", input_list)
    print("Hasil konversi ke tuple:", tuple_result)

list_ke_tuple()

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')

a = ('1021, 1022, 1023', '1025, 1026, 1027', '1029, 1030, 1030')
print(a)
def rata_rata(angka):
    rata_rata = [int(x) for x in angka.split(', ')]
    return int(sum(rata_rata) / len(rata_rata))

averages = [rata_rata(group) for group in a]
print(f"rata rata dari tuple adalah : {averages} ")

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')
a = [8,2,1,4]
print(a)
hasil = 1
for result in a:
    hasil *= result
print(hasil)

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')
def hitung_jumlah_string_sama(list_string):
    jumlah = 0
    for string in list_string:
        if len(string) >= 2 and string[0] == string[-1]:
            jumlah += 1
    return jumlah

input_strings = input("Masukkan list string (pisahkan dengan koma): ")
list_string = [s.strip() for s in input_strings.split(',')]
jumlah_string_sama = hitung_jumlah_string_sama(list_string)
print(f"Jumlah string dengan panjang minimal 2 dan karakter pertama serta karakter terakhirnya sama adalah: {jumlah_string_sama}")